---
- hosts: corbt
  user: deploy
  sudo: true
  gather_facts: false

  vars_files:
    - vars/defaults.yml
    - vars/secrets.yml

  roles:
    - {role: seafile, tags: ['seafile']}
    - {role: transmission, tags: ['transmission']}

  tasks:
    - include: tasks/bootstrap.yml tags=bootstrap
    - include: tasks/systemd.yml tags=systemd
    - include: tasks/ruby.yml tags=ruby
    - include: tasks/nginx.yml tags=nginx

    - name: Create file structure
      file: path={{item}} owner=deploy group=deploy state=directory
      with_items:
        - /srv/www/corbt
        - /srv/www/corbt/downloads
        - /srv/www/corbt/torrents
        - /home/deploy/.transmission/config

    - name: Install nginx-proxy
      template: src=templates/nginx-proxy.service.j2 dest=/etc/systemd/system/nginx-proxy.service
      notify: enable nginx-proxy

    - name: Install transmission
      template: src=templates/transmission.service.j2 dest=/etc/systemd/system/transmission.service
      notify: enable transmission

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: enable transmission
      command: "{{item}}"
      with_items:
        - systemctl enable /etc/systemd/system/transmission.service 
        - systemctl daemon-reload 
        - systemctl restart transmission.service

    - name: reload grub
      command: update-grub

    - name: reboot
      command: /sbin/reboot