---
- hosts: corbt
  user: deploy
  sudo: true
  gather_facts: false

  vars_files:
    - vars/defaults.yml
    - vars/secrets.yml

  roles:
    - {role: nginx, tags: ['nginx']}
    - {role: seafile, tags: ['seafile']}
    - {role: transmission, tags: ['transmission']}
    - {role: openvpn, tags: ['openvpn']}

  tasks:
    - include: tasks/bootstrap.yml tags=bootstrap
    - include: tasks/systemd.yml tags=systemd
    - include: tasks/ruby.yml tags=ruby
    - include: tasks/blog.yml tags=blog

  handlers:
    - name: reload grub
      command: update-grub

    - name: reboot
      command: /sbin/reboot