---
- name: Download openvpn
  get_url: url=http://swupdate.openvpn.org/as/{{openvpn.version}}.deb dest=/root/openvpn.deb force=no

- name: Install openvpn
  apt: deb=/root/openvpn.deb state=installed

- name: Set the openvpn password
  user: name=openvpn password={{openvpn_password}}

- name: Render nginx template
  template: src=openvpn-nginx.conf.j2 dest=/etc/nginx/sites-enabled/openvpn.conf
  notify: restart nginx

- name: Open the tunnel port
  ufw: rule=allow proto=udp port=1194

# - name: tmp allow direct
#   ufw: rule=allow port=943

# NOTE: if you are unable to connect to the openVPN server after this playbook runs, try running, on the server,
# sudo /usr/local/openvpn_as/bin/ovpn-init --force
# Go through the install process and leave everything as default, except tell it to
# listen on all interfaces (0.0.0.0) instead of just the default one. Not sure if this is necessary or
# not but worth a shot.